# Generated by Django 2.1.5 on 2019-02-05 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complet', models.BooleanField(default=False, verbose_name='Terminé')),
                ('date_creation', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objet', models.CharField(max_length=200, verbose_name='Objet du message')),
                ('date_message', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi du message")),
                ('content', models.TextField(verbose_name='Contenu du message')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raison', models.CharField(max_length=200)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('telephone', models.CharField(max_length=15)),
                ('adresse', models.CharField(max_length=150)),
                ('numsecu', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('adresse', models.CharField(max_length=150)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Document')),
                ('fichier', models.FileField(upload_to='')),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Hopital',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Structure')),
                ('logo', models.ImageField(upload_to='updd/static/media')),
            ],
        ),
        migrations.CreateModel(
            name='Infirmier',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Medecin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Document')),
                ('type', models.CharField(max_length=20, verbose_name="Type de l'opération")),
                ('libelle', models.CharField(max_length=100, verbose_name="Libelle de l'opération")),
            ],
        ),
        migrations.CreateModel(
            name='Ordonnance',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Document')),
                ('texte', models.TextField(verbose_name='Contenu ordonnace')),
            ],
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Structure')),
                ('hopital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.Hopital')),
            ],
        ),
        migrations.CreateModel(
            name='Secretaire',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Structure')),
                ('pole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.Pole')),
            ],
        ),
        migrations.CreateModel(
            name='Soin',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Document')),
                ('texte', models.TextField(verbose_name='Contenu fiche de soin')),
            ],
        ),
        migrations.CreateModel(
            name='UH',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Structure')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.Service')),
            ],
        ),
        migrations.CreateModel(
            name='US',
            fields=[
                ('structure', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='updd.Structure')),
                ('uh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.UH')),
            ],
        ),
        migrations.AddField(
            model_name='notification',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_envoye', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_recu', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.Patient'),
        ),
        migrations.AddField(
            model_name='document',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.Personnel', verbose_name='Auteur'),
        ),
        migrations.AddField(
            model_name='document',
            name='dossier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.DossierMedical'),
        ),
        migrations.AddField(
            model_name='patient',
            name='hospitalisation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.US'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='dirigep',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dirige_pole', to='updd.Pole'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='diriges',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dirige_service', to='updd.Service'),
        ),
        migrations.AddField(
            model_name='medecin',
            name='dossiermedical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='updd.DossierMedical', verbose_name='Dossier medical'),
        ),
    ]
