# Generated by Django 2.1.5 on 2019-02-05 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='updd.Patient'),
        ),
    ]
