# Generated by Django 2.1.5 on 2019-02-12 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updd', '0003_auto_20190206_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='affectation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='updd.Service'),
        ),
    ]
