# Generated by Django 2.1.5 on 2019-02-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updd', '0005_auto_20190212_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='complet',
            field=models.BooleanField(default=False, verbose_name='Terminé'),
        ),
    ]
