# Generated by Django 2.1.5 on 2019-02-26 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('updd', '0006_ordonnance_complet'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordonnance',
            name='commanditaire',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='updd.Medecin', verbose_name='Commanditaire'),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_recu', to=settings.AUTH_USER_MODEL, verbose_name='Destinataire'),
        ),
    ]
